services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    # depends_on:
    #   - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
