services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13
  #   container_name: my-express-db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
